### ISSUE TITLE
How to render a simply sphere with texture?

### ISSUE THREAD

**Issue by laobel** [toji/webgpu-metaballs#1]
Hi, your code helps me a lot. I have a question for you.
I hope to add a case study of texturedSphere example.
Thanks a lot !

**Comment by toji** [comment]
If you want to draw a sphere geometry with a texture on it, you'd basically want to look at any example that draws any textured shape (such as http://austin-eng.com/webgpu-samples/samples/texturedCube) and modify the vertex data (like https://github.com/austinEng/webgpu-samples/blob/main/src/meshes/cube.ts) to instead describe a sphere.

Fortunately that's pretty easy to compute mathematically. You can take a look at something like the Three.js SphereGeometry code to get an idea of how it's done: https://github.com/mrdoob/three.js/blob/dev/src/geometries/SphereGeometry.js#L40

**Comment by laobel** [comment]
@toji I am very happy to receive your reply.I drew a sphere as you suggested，but the texture is wrong( shown in the screenshot below),What is the problem?
![image](https://user-images.githubusercontent.com/17061454/125553565-eb232d21-5389-493b-a17f-931fc3cbb2cd.png)

**Comment by toji** [comment]
There are several things that might be going on there, it's hard to tell from just a screenshot. My suspicion is that you've generated mesh data that is intended to be drawn with `.drawIndexed()` but are instead drawing with `.draw()`. If you copied the math from the Three.js code I linked earlier then that's almost certainly the case. To use indexed rendering you'll need to generate an index buffer that defines the order in which the vertices you've already created should be connected as triangles. (The Three.js math for a sphere's index buffer is here: https://github.com/mrdoob/three.js/blob/dev/src/geometries/SphereGeometry.js#L93)

A quick thing you can do before that, however, to check an make sure your vertices are where you expect them, it to find where you are calling `.createRenderPipeline()` and change the `topology` to `"point-list". This render each vertex as just a point without trying to connect them together, and let you see if the general shape is the one you want before going any further.
