### ISSUE TITLE
Chrome memory shoots up when using a ring of staging buffers (Windows 10)

### ISSUE THREAD

**Issue by arcman7** [toji/webgpu-metaballs#2]
Here's the script I used to test:

```




async function init() {
  if (!navigator.gpu) {
    throw Error("WebGPU not supported.");
  }

  const adapter = await navigator.gpu.requestAdapter();
  if (!adapter) {
    throw Error("Couldn't request WebGPU adapter.");
  }

  window.gpuDevice = await adapter.requestDevice();
  var waveGridSize = 1024 * 2;
  var height = Math.floor(Math.sqrt(waveGridSize));
  var width = height;
  var waveGridBufferSize = waveGridSize * waveGridSize * 7 * Float32Array.BYTES_PER_ELEMENT;
  var waveGridVertexBuffer = gpuDevice.createBuffer({
    size: waveGridBufferSize,
    usage: GPUBufferUsage.VERTEX | GPUBufferUsage.COPY_DST,
  });
  var waveGridStagingBuffers = [];
  // Updates a grid of vertices on the X, Y plane with wave-like motion
  function updateWaveGrid(time, gpuDevice) {
    // Get a new or re-used staging buffer that's already mapped.
    let stagingBuffer;
    if (waveGridStagingBuffers.length) {
      console.log('using existing staging buffer');
      stagingBuffer = waveGridStagingBuffers.pop();
    } else {
      console.warn('creating new staging buffer')
      stagingBuffer = gpuDevice.createBuffer({
        size: waveGridBufferSize,
        usage: GPUBufferUsage.MAP_WRITE | GPUBufferUsage.COPY_SRC,
        mappedAtCreation: true,
      });
    }

    // Fill in the vertex grid values.
    const vertexPositions = new Float32Array(stagingBuffer.getMappedRange());
    for (let y = 0; y < height; ++y) {
      for (let x = 0; x < width; ++x) {
        const vertexIndex = y * width + x;
        const offset = vertexIndex * 7;

        vertexPositions[offset + 0] = x;
        vertexPositions[offset + 1] = y;
        vertexPositions[offset + 2] = Math.sin(time + (x + y) * 0.1);
        vertexPositions[offset + 3] = Math.sin(time + (x + y) * 0.1);;
        vertexPositions[offset + 4] = Math.sin(time + (x + y) * 0.1);
        vertexPositions[offset + 5] = Math.sin(time + (x + y) * 0.1);
        vertexPositions[offset + 6] = Math.sin(time + (x + y) * 0.1);
      }
    }
    stagingBuffer.unmap();

    // Copy the staging buffer contents to the vertex buffer.
    const commandEncoder = gpuDevice.createCommandEncoder({});
    commandEncoder.copyBufferToBuffer(stagingBuffer, 0, waveGridVertexBuffer, 0, waveGridBufferSize);
    gpuDevice.queue.submit([commandEncoder.finish()]);

    // Immediately after copying, re-map the buffer. Push onto the list of staging buffers when the
    // mapping completes.
    stagingBuffer.mapAsync(GPUMapMode.WRITE).then(() => {
      waveGridStagingBuffers.push(stagingBuffer);
    });
  }

  var prevTime = 0
  function frameCallback(time) {
    // console.log(time - prevTime);
    prevTime = time;
    performance.mark('frameStart');
    updateWaveGrid(time, window.gpuDevice)
    performance.mark('frameEnd');
    console.log(performance.measure('frame', 'frameStart', 'frameEnd'))
    window.requestAnimationFrame(frameCallback);
  }
  window.requestAnimationFrame(frameCallback);
}

init();
```

I would ran this directly in the console. Here's a screenshot of the output that gets printed to the console:

![image](https://github.com/toji/webgpu-metaballs/assets/9598327/df77334c-32d4-4a54-985d-8d886d80d765)

Over time, I get more gpu buffers in the ring, and eventually the number of times a new buffer is created with respect to using an existing buffer starts to diminish, but by then, the chrome process is using an additional 4.5GB of ram. Soon after, everything just freezes.  I'm not sure what I'm doing wrong here.

**Comment by arcman7** [comment]
I changed the size of the buffer being copied from
```
var waveGridBufferSize = waveGridSize * waveGridSize * 7 * Float32Array.BYTES_PER_ELEMENT;
```
to

```
var waveGridBufferSize = waveGridSize * 7 * Float32Array.BYTES_PER_ELEMENT;
```

And it quickly stabilizes at 3 buffers in the ring. But the chrome memory process continues to slowly grow, about 100MB per minute. If I pause the execution of the code from the console debugger, then it I see the memory usage of the chrome process go back down. 

This issue doesn't happen on your [demo ](https://toji.github.io/webgpu-metaballs/) when using the ring of staging buffers option.

**Comment by toji** [comment]
I'm not entirely sure why the memory continues to grow like that, and it's hard to debug without a live page to test. I will say that there's a known quirk where the JavaScript garbage collector doesn't recognize the internal size of a WebGPU buffer as contributing to it's memory pressure, and so it's possible to create a lot of large WebGPU buffers that then fail to ever trigger garbage collection. Ironically, this means that fairly simple demos can appear to "leak" while more complex ones (that usually have other factors that provoke garbage collection) have more stable memory usage.

Not sure if that's what's happening here, since you should have a relatively stable "cap" to your GPU allocations, but it's the only thing that comes to mind.

**Comment by yanglebupt** [comment]
I think the possible reason is that `mapAsync` is slow but the frame interval is fast relatively. Once `mapAsync` is not completed, a new gpuBuffer will be created when each frame is retrieved from the ring. And you changed the size of the buffer to larger, `mapAsync` will require more time, resulting in an increasing number of GPU buffer creations

**Comment by yanglebupt** [comment]
In the code comments section, the author wrote a disadvantage, I'm not sure if it refers to this issue ?
<img width="406" alt="屏幕截图 2024-06-30 230337" src="https://github.com/toji/webgpu-metaballs/assets/139488963/4fc455ea-5c83-47ef-ac9d-dd14662e5785">

**Comment by arcman7** [comment]
You're right and I missed that note there in the comment. Having tested it for increasingly large buffers, I think the observed behavior on my end is in line with what you've brought forth here in the discussion.
